---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: openstax/rap-spike-bridge
    tag: latest

params:
  DB_URL: ((db_url))

inputs:
  - name: identifier-struct

outputs:
  - name: content

run:
  path: sh
  args:
    - -c
    - |
      # DEBUG info
      env
      ls -lah
      ls -lah identifier-struct
      # Working logic
      echo "Extracting: $(cat identifier-struct/ident_hash)"
      bridge extract -o content/ $(cat identifier-struct/ident_hash)
