version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    # Note, we use the concourse release candidate, because
    # the concourse/concourse image has a known flaw.
    # See also, https://github.com/concourse/concourse/issues/3758
    image: concourse/concourse-rc
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
    links:
      - content-events-api

  cnx-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  cnx-db:
    image: openstax/cnx-db:latest
    # For development usage, use something like the following
    # build:
    #   context: https://github.com/Connexions/cnx-db.git#master
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  content-events-api:
    build: api/
    ports:
      - "5000:5000"
    volumes:
      - ./api:/code
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

  bridge-resource:
    build: bridge/
    command: tail -f /dev/null
    environment:
      - BRIDGE_AWS_REGION=us-east-2
      - BRIDGE_AWS_BUCKET=ce-rap-test
    volumes:
      - ./bridge/src/bridge:/usr/local/lib/python3.7/site-packages/bridge

volumes:
  pg-data:
