---

resources:
  - name: recent-rss
    type: rss
    check_every: 10m
    source:
      url: "https://((target-domain))/feeds/recent.rss?number=100&type=Collection"
  - name: notify-slack
    type: slack
    source:
      url: ((slack-webhook-url))

resource_types:
  # TODO: Fork these so we own the images and therefore can audit changes.
  - name: slack
    type: docker-image
    source:
      # Original is not up-to-date
      # repository: cfcommunity/slack-notification-resource
      repository: pumazi/concourse-slack-notification-resource
      tag: latest
  - name: rss
    type: docker-image
    source:
      repository: suhlig/concourse-rss-resource
      tag: latest

jobs:
  - name: publishing-feed
    public: true
    plan:
      - get: recent-rss
        trigger: true
      - get: notify-slack
      - task: build-env-file
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          inputs:
            - name: recent-rss
          outputs:
            - name: env-vars
          run:
            path: sh
            # FIXME: The description is multi-line, so I've left it out for now.
            args:
              - -c
              - |
                cat << EOF > env-vars/env_file
                title=$(cat recent-rss/title)
                link=$(cat recent-rss/link | sed 's/\(archive\)[-.]//g')
                pubDate=$(cat recent-rss/pubDate)
                guid=$(cat recent-rss/guid)
                EOF
                echo "cat the env_file for debug purposes"
                cat env-vars/env_file
      - put: notify-slack
        params:
          text: ":books: <$link|$title> was successfully published :tada::cake::tada:"
          env_file: env-vars/env_file
