---

###
#  Resources
###

resources:

  - name: bridge
    type: docker-image
    source:
      repository: openstax/rap-spike-bridge
      # tag: latest
      tag: 1.1.0

###
#  Resource Types
###

resource_types:

###
#  Pipeline Jobs
###

jobs:
  - name: extract-content
    public: true
    plan:

      # mock the identifier-struct (data structure coming from the content-event-resource)
      - task: mock-identifier-struct
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          outputs:
            - name: mock-struct
          params:
            IDENT_HASH: "4b5aaf32-1de1-419b-bdc0-4e0a7f6daf0f@27"
          run:
            path: sh
            args:
              - -c
              - |
                touch mock-struct/id
                echo $IDENT_HASH > mock-struct/ident_hash
                touch mock-struct/event.json
        
      - get: bridge

      - task: extraction
        image: bridge
        file: bridge/rootfs/tasks/extract-content.yml
        vars:
          db_url: "postgresql://rhaptos@cnx-db/repository"
        input_mapping:
          identifier-struct: mock-struct
        output_mapping:
          content: content

      - task: print
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          inputs:
            - name: content
          run:
            path: sh
            args:
              - -c
              - |
                ls -lah content
                cat content/d9f43d2e5393356e06c755ff947bd31327fa5edc
                echo '--------------------'
                cat content/archive-response.raw.json
